#! /bin/bash

setup_home=$(pwd)

if [ -f "${setup_home}"/bash/bsfl ]
then
    . "${setup_home}"/bash/bsfl
else
    echo "Missing dependency - bsfl..."
    exit -1
fi

cmd "rm ${HOME}/.bashrc"
cmd "rm ${HOME}/.bash_logout"
cmd "rm ${HOME}/.gitconfig"
cmd "rm ${HOME}/.gitignore"
cmd "rm ${HOME}/.gvimrc"
cmd "rm ${HOME}/.inputrc"
cmd "rm ${HOME}/.profile"
cmd "rm ${HOME}/.tigrc"
cmd "rm ${HOME}/.tmux.conf"
cmd "rm ${HOME}/.vimrc"
cmd "rm -fr ${HOME}/.clinit.d"
cmd "rm -fr ${HOME}/.vim"
