:set lines=60
:set columns=130
" :set gfn=Ubuntu\ Mono\ derivative\ Powerline\ 10
:set gfn=DejaVu\ Sans\ Mono\ for\ Powerline\ 9 
:set background=dark
:set guioptions-=m
:set guioptions-=r
:set guioptions-=T
:colorscheme solarized

