#!/bin/bash
for directory in $(find ./ -maxdepth 1 -type d | sed -e 's/^\.\///' | sed -e '/^$/d' | sort)
do
    cd ${directory}
    here=${PWD}
    repo=$(git remote -v | grep push | sed -e 's/origin//' | sed -e 's/(push)//')
    pair=$"${repo} ${here}"
    echo ${pair}
    cd ..
done

