filetype off

execute pathogen#infect()
execute pathogen#helptags()

" ---------------------------------------------------------------------------
" operational settings
filetype indent plugin on       " automatic file type detection
set modeline                    " turn on modeline
set cursorline                  " highlight current line
set nocompatible                " vim defaults, not vi!
set hidden                      " allow editing multiple unsaved buffers
set more                        " the 'more' prompt
set autoread                    " watch for file changes by other programs
set visualbell                  " visual beep
set backup                      " produce *~ backup files
set noautowrite                 " don't automatically write on :next, etc
set wildmenu                    " : menu has tab completion, etc
set scrolloff=5                 " keep at least 5 lines above/below cursor
set sidescrolloff=5             " keep at least 5 columns left/right of cursor
set history=200                 " remember the last 200 commands
set shell=bash
syntax enable
syntax on                       " syntax on

" ---------------------------------------------------------------------------
" syntastic settings
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_check_on_wq              = 0

" ---------------------------------------------------------------------------
" backup settings
set backupdir=/home/axl/.vimbackups,.
set directory=/home/axl/.vimbackups,.
au BufWritePre * let &bex = '@' . strftime("%Y-%m-%dT%H:%M:%S")

" ---------------------------------------------------------------------------
" window spacing
set cmdheight=2                 " make command line two lines high
set lazyredraw                  " don't redraw when running macros
set number                      " show line number on each line
set relativenumber              " show relative line number
set laststatus=2

" ---------------------------------------------------------------------------
" mouse settings
set mouse=a                     " mouse support in all modes
set mousehide                   " hide the mouse when typing text

" ,p and shift-insert will paste the X buffer, even on the command line
nmap <LocalLeader>p i<S-MiddleMouse><ESC>
imap <S-Insert> <S-MiddleMouse>
cmap <S-Insert> <S-MiddleMouse>

" this makes the mouse paste a block of text without formatting it
" (good for code)
map <MouseMiddle> <esc>"*p

" ---------------------------------------------------------------------------
" global editing settings
set autoindent smartindent      " turn on auto/smart indenting
set expandtab                   " use spaces, not tabs
set smarttab                    " make <tab> and <backspace> smarter
set tabstop=4                   " tabstops of 4
set softtabstop=4
set shiftwidth=4                " indents of 4
set backspace=eol,start,indent  " allow backspacing over indent, eol, & start
set colorcolumn=90              " right margin at 90 columns
set undolevels=100              " number of forgivable mistakes
set updatecount=100             " write swap file to disk every 100 chars
set complete=.,w,b,u,U,t,i,d    " do lots of scanning on tab completion
set viminfo=%100,'100,/100,h,\"500,:100,n~/.viminfo
set linebreak

" ---------------------------------------------------------------------------
" searching...
set incsearch                  " show matches as soon as possible
set hlsearch                   " enable search highlight globally
set showmatch                  " show matching brackets when typing

set diffopt=filler,iwhite       " ignore all whitespace and sync

" ---------------------------------------------------------------------------
" mappings
" Y yanks from cursor to $
map Y y$
" toggle Undo Tree...
nnoremap <F8> :GundoToggle<CR>
" yep, toggle NERDTree...
nmap <F9> :NERDTreeToggle<CR>
" and TagBar too...
nmap <F10> :TagbarToggle<CR>
" toggle invisible characters
set listchars=tab:▸\ ,eol:¬
nmap <leader>h :set list!<CR>

" shortcuts
inoremap <expr> vdts strftime("%y%m%d%H%M%S")
inoremap <expr> idts strftime("%FT%T%z")
inoremap <expr> axlg "Axl Mattheus <axl.mattheus@gmail.com>"
inoremap <expr> axlm "Axl Mattheus <axl.mattheus@microsoft.com> (@Microsoft)"
inoremap <expr> axla "Axl Mattheus <axl.mattheus@annaxxko.net> (@annaxxKØ)"

"set foldmethod=expr
set foldmethod=syntax


" solarized
" let g:solarized_bold       = 1
" let g:solarized_italic     = 1
" let g:solarized_underline  = 0
colorscheme solarized
" colorscheme monokai
" if $SOLARIZED == "LIGHT"
    " set background=light
" else
    " set background=dark
" endif

" erlang
let erlang_folding  = 1
let erlang_skel_dir = "/home/axl/vim/skeletons/erlang"

" rust
let g:racer_cmd   = "/home/axl/.cargo/bin/racer"
let $RUST_SRC_PATH="/home/axl/Projects/GitHub/lang-rust/src/"

" dictionary
set dictionary=/usr/share/dict/words            " used with CTRL-X CTRL-K
:map <F5> :setlocal spell! spelllang=en_uk<CR>

" status line
set laststatus=2  " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
if $POWERLINE != "ON"
    set statusline=%<%f\ %y\ %h%m%r%=%-14.([%n]\ %l,%c%V%)\ %P
endif
if $POWERLINE == "ON"
    set noshowmode    " Hide the default mode text (e.g. -- INSERT -- below the statusline)
    set rtp+=/home/axl/.local/lib/python3.5/site-packages/powerline/bindings/vim
endif

