filetype off

execute pathogen#infect()
execute pathogen#helptags()

" ---------------------------------------------------------------------------
" operational settings
set modeline                    " turn on modeline
set cursorline                  " highlight current line
set nocompatible                " vim defaults, not vi!
set hidden                      " allow editing multiple unsaved buffers
set more                        " the 'more' prompt
set autoread                    " watch for file changes by other programs
set visualbell                  " visual beep
set backup                      " produce *~ backup files
set noautowrite                 " don't automatically write on :next, etc
set wildmenu                    " : menu has tab completion, etc
set scrolloff=5                 " keep at least 5 lines above/below cursor
set sidescrolloff=5             " keep at least 5 columns left/right of cursor
set history=200                 " remember the last 200 commands
filetype indent plugin on       " automatic file type detection
syntax enable
syntax on                       " syntax on

" ---------------------------------------------------------------------------
" backup settings
set backupdir=~/.vimbackup,.
set directory=~/.vimbackup,.
au BufWritePre * let &bex = '@' . strftime("%Y-%m-%dT%H:%M:%S")

" ---------------------------------------------------------------------------
" window spacing
set cmdheight=2                 " make command line two lines high
set lazyredraw                  " don't redraw when running macros
set number                      " show line number on each line
set laststatus=2

" ---------------------------------------------------------------------------
" mouse settings
set mouse=a                     " mouse support in all modes
set mousehide                   " hide the mouse when typing text

" ,p and shift-insert will paste the X buffer, even on the command line
nmap <LocalLeader>p i<S-MiddleMouse><ESC>
imap <S-Insert> <S-MiddleMouse>
cmap <S-Insert> <S-MiddleMouse>

" this makes the mouse paste a block of text without formatting it
" (good for code)
map <MouseMiddle> <esc>"*p

" ---------------------------------------------------------------------------
" global editing settings
set autoindent smartindent      " turn on auto/smart indenting
set expandtab                   " use spaces, not tabs
set smarttab                    " make <tab> and <backspace> smarter
set tabstop=4                   " tabstops of 4
set shiftwidth=4                " indents of 4
set backspace=eol,start,indent  " allow backspacing over indent, eol, & start
set undolevels=100              " number of forgivable mistakes
set updatecount=100             " write swap file to disk every 100 chars
set complete=.,w,b,u,U,t,i,d    " do lots of scanning on tab completion
set viminfo=%100,'100,/100,h,\"500,:100,n~/.viminfo
set linebreak

" ---------------------------------------------------------------------------
" searching...
set incsearch                  " show matches as soon as possible
set hlsearch                   " enable search highlight globally
set showmatch                  " show matching brackets when typing

set diffopt=filler,iwhite       " ignore all whitespace and sync

" ---------------------------------------------------------------------------
" some useful mappings
" Y yanks from cursor to $
map Y y$
" word swapping
nmap <silent> gw "_yiw:s/\(\%#\w\+\)\(\W\+\)\(\w\+\)/\3\2\1/<cr><c-o><c-l>
" char swapping
nmap <silent> gc xph
" yep, toggle NERDTree...
nmap <F9> :NERDTreeToggle<CR>
" and TagBar too...
nmap <F10> :TagbarToggle<CR>

"set foldmethod=expr
set foldmethod=syntax


if $TERM =~ '^xterm'
    set t_Co=256
elseif $TERM =~ '^screen-bce'
    set t_Co=256            " just guessing
elseif $TERM =~ '^rxvt'
    set t_Co=88
elseif $TERM =~ '^linux'
    set t_Co=8
else
    set t_Co=16
endif

set background=dark
colorscheme solarized

let $kernel_version=system('uname -r | tr -d "\n"')
set tags=./tags,tags,../tags,../../tags,../../../tags,../../../../tags,/lib/modules/$kernel_version/build/tags,/usr/include/tags

let erlang_folding = 1


set dictionary=/usr/share/dict/words            " used with CTRL-X CTRL-K
:map <F5> :setlocal spell! spelllang=en_uk<CR>

execute pathogen#infect()

if $POWERLINE != "ON"
    set statusline=%<%f\ %y\ %h%m%r%=%-14.([%n]\ %l,%c%V%)\ %P
endif
if $POWERLINE == "ON"
    set rtp+=$CLINIT_HOME/dependencies/powerline/powerline/bindings/vim
endif


