#!/bin/bash
DARK_PALETTE="#070736364242:#D3D301010202:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"
DARK_BG="#00002B2B3636"
DARK_FG="#65657B7B8383"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile0/use_theme_background" --type bool false
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile0/use_theme_colors" --type bool false
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile0/palette" --type string "$DARK_PALETTE"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile0/background_color" --type string "$DARK_BG"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile0/foreground_color" --type string "$DARK_FG"

LIGHT_PALETTE="#EEEEE8E8D5D5:#D3D301010202:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#070736364242:#FDFDF6F6E3E3:#CBCB4B4B1616:#9393A1A1A1A1:#838394949696:#65657B7B8383:#6C6C7171C4C4:#58586E6E7575:#00002B2B3636"
LIGHT_BG="#FDFDF6F6E3E3"
LIGHT_FG="#838394949696"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile1/use_theme_background" --type bool false
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile1/use_theme_colors" --type bool false
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile1/palette" --type string "$LIGHT_PALETTE"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile1/background_color" --type string "$LIGHT_BG"
gconftool-2 --set "/apps/gnome-terminal/profiles/Profile1/foreground_color" --type string "$LIGHT_FG"

