#!/bin/bash
if [ -n "${1}" ]
then
    tmux new-session -s "${1}" -n editor -d
    tmux split-window -h -l 120 -t "${1}" "fish"
    tmux split-window -v -l 32 -t "${1}" "fish"
    tmux send-keys -t 2 "clear" Enter
    tmux send-keys -t 3 "clear" Enter
    tmux select-pane -t 1
    tmux attach -t "${1}"
else
    . "${CLINIT_HOME}"/bash/bsfl
    msg "Missing session name"
    msg "Synopsys:"
    msg "    tmd <name>"
fi

