#!/bin/bash
# hard-coded, fix...
. ~/.clinit.d/bash/bsfl

if [ -n "${1}" ]
then
    tmux new-session -s "${1}" -n editor -d
    tmux split-window -h -l 129 -t "${1}"
    tmux split-window -v -l 32 -t "${1}"
    tmux select-pane -t 1
    tmux attach -t "${1}"
else
    msg "Missing session name"
    msg "Synopsys:"
    msg "    tmdev <name>"
fi

