#!/bin/bash
if [ -n "${1}" ]
then
    TERM=screen-256color tmux new-session -s "${1}" -n scratch "fish"
else
    . "${CLINIT_HOME}"/bash/bsfl
    msg "Missing session name"
    msg "Synopsys:"
    msg "    tms <name>"
fi

