#! /bin/bash

SESSION="${1:-"main"}"
WINDOW="${2:-"bash"}"
DIRECTORY="${3:-"$(pwd)"}"
tmux new-session -s "${SESSION}" -n "${WINDOW}" -d
tmux split-window -t "${SESSION}" -h -p 55
tmux split-window -t "${SESSION}" -v -p 50
tmux send-keys -t "${SESSION}":1.1 "cd "${DIRECTORY}"" C-m
tmux send-keys -t "${SESSION}":1.2 "cd "${DIRECTORY}"" C-m
tmux send-keys -t "${SESSION}":1.3 "cd "${DIRECTORY}"" C-m
tmux send-keys -t "${SESSION}":1.1 "clear" C-m
tmux send-keys -t "${SESSION}":1.2 "clear" C-m
tmux send-keys -t "${SESSION}":1.3 "clear" C-m
tmux attach -t "${SESSION}"

