#! /bin/bash

SESSION="${1:-"main"}"
WINDOW="${2:-"bash"}"
tmux new-session -s "${SESSION}" -n "${WINDOW}" -d
tmux split-window -t "${SESSION}" -h -p 55
tmux split-window -t "${SESSION}" -v -p 50
tmux attach -t "${SESSION}"

