#! /bin/bash

# system replacement functionions
if [ -n "$PS1" ] ; then
    rm ()
    {
        ls -sd "$@"
        echo 'remove[ny]? ' | tr -d '\012' ; read
        if [ "_$REPLY" = "_y" ]; then
            /bin/rm -vrf "$@"
        else
            echo '(cancelled)'
        fi
    }
fi

if [ -n "$PS1" ] ; then
    if [ -f $(which srm) ] ; then
        srm ()
        {
            ls -sd "$@"
            echo 'remove[ny]? ' | tr -d '\012' ; read
            if [ "_$REPLY" = "_y" ]; then
                $(which srm) -vrf "$@"
            else
                echo '(cancelled)'
            fi
        }
    else
      echo 'srm is not installed.'
      echo 'Try installing it with apt-get install secure-delete on Ubuntu.'
    fi
fi

random_password () {
    local __length="${1:-37}"
    < /dev/urandom tr -dc '[[:alnum:][:punct:]]' | head -c${__length}
    echo
}
