# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias colorls='ls --color=auto '
    alias colordir='dir --color=auto '

    alias colorgrep='egrep --color=auto '
    alias colorfgrep='GREP_COLORS=fn=93:ln=96:se=93 fgrep --color=auto '
    alias colorrgrep='rgrep --color=auto '
    alias colorpgrep='pcregrep --color=auto '
fi

# ALIASES
# shells, TODO, make sure solarized color schemes for gnome-terminal is installed
alias solarized-dark-fish="gnome-terminal --command=fish --window-with-profile=\"Solarized Dark\""
alias solarized-light-fish="gnome-terminal --command=fish --window-with-profile=\"Solarized Light\""
# shortcut
alias cp='cp -uv '
alias lsmnt='mount | column -t | grep ^\/dev '
alias lsrm='yes no | /bin/rm -ri '
alias mem='cat /proc/meminfo '
alias mv='mv -uv '
alias ssh='TERM=xterm ssh -X '
alias sweep='find . -iname **~ -type f -exec mv2trash {} \; '
alias top='htop '
alias tree-list-directories='tree -d '
alias tree='tree -F -I *~ '
alias xmlprety='xmllint --format '
alias xmltidy='tidy -w 100 -q -i -xml '
# date
alias date-iso8601='date +%Y-%m-%dT%H:%M:%S '
alias date-sync='sudo ntpdate ntp.ubuntu.com '
alias date-timestamp-nanos='date +%Y%m%d%H%M%S%N '
alias date-timestamp='date +%Y%m%d%H%M%S '
# directory
alias ...='cd ../.. '
alias ..='cd .. '
alias :q='exit '
alias cd..='cd ..'
alias df='df -h '
alias dir='colordir '
alias du='du -h '
alias size='du -shx '
# find
alias fgrep='colorfgrep '
alias grep='colorgrep '
alias ngrep='grep -v '
alias rgrep='colorrgrep '
alias pgrep='colorpgrep '
# list
alias l1='ls -1 '
alias l='l1 '
alias lN='ls -n '
alias lS='ls -S '
alias la='ls -A '
alias li='ll -i '
alias ll='ls -l -k -h '
alias llS='ll -S '
alias lld='tree -ifd --noreport --dirsfirst '
alias llf='tree -if --noreport '
alias ls='colorls --hide='*~' --hide='.*~' -F -I CVS --group-directories-first -X '
alias lsb='find . -iname **~ -type f 2>/dev/null '
alias lsd='find "$(pwd)" -mindepth 1 -maxdepth 1 -type d | sort '
alias lsf='find "$(pwd)" -maxdepth 1 -type f | sort '
# misc
alias mark='echo -e "\n ================== $(date-iso8601) =================\n" '
alias matrix-green='MATRIX_COLOR="${GREEN_MATRIX}" matrix '
alias matrix-red='MATRIX_COLOR="${RED_MATRIX}" matrix '
# python
alias python='python3 '
# ruby
alias ruby='ruby2.0 '
alias irb='irb2.0 '
# r?
alias r='fc -s '
# tmux
alias tmux-attach='tmux attach-session -t '
alias tmux-kill='tmux kill-session -t '
alias tmux-list='tmux list-sessions '
alias tmux-session='tmux new-session -s '
alias tma='tmux attach-session -t '
alias tmd='~/Projects/GitHub/clinit/tmux/tmd '
alias tme='~/Projects/GitHub/clinit/tmux/tme '
alias tmk='tmux kill-session -t '
alias tml='tmux list-sessions '
alias tms='tmux new-session -s '
alias tmvim='TERM=screen-256color vim '
alias tmtop='TERM=screen-256color top '
alias tmaliases='cat ~/Projects/GitHub/clinit/bash/bash_aliases | grep --color=never "^alias tm" '
# vim
alias vimless='tmvim -u /usr/share/vim/vim74/macros/less.vim '
# incognito
alias I=' ' # everything prepended with I, followed by a space will not show up in history!

