# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Source global completions
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# shell options
set -o vi
shopt -s cdable_vars
shopt -s checkwinsize
shopt -s histappend
shopt -s cdspell
shopt -s cmdhist
shopt -s extglob
HISTFILESIZE=1000
HISTSIZE=250
HISTCONTROL=ignoreboth:erasedups
export HISTIGNORE="I*:clear:ls*:fg:exit:history*:[ \t]*:&"

# exports
export TERM=xterm-256color
export CLINIT_HOME="${HOME}"/.clinit.d
export POWERLINE="OFF"


# echo "Session name [main]: "
# read name
# [[ -z "${TMUX}" ]] && exec $(tmux new-session -s ${name})

. "${CLINIT_HOME}"/bash/bsfl
. "${CLINIT_HOME}"/bash/bash_aliases
. "${CLINIT_HOME}"/bash/bash_functions
. "${CLINIT_HOME}"/bash/bash_colors

# prompt
if [ -d ${ENVCFG_HOME}/bash/powerline.sh ]; then
    # powerline
    . ~/.envcfg/init.d/bash/powerline.sh
elif file_exists "${CLINIT_HOME}"/bash/bash_prompt ; then
    # colors prompts
     . "${CLINIT_HOME}"/bash/bash_prompt
fi

