# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Source global completions
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# shell options
set -o vi
shopt -s cdable_vars
shopt -s checkwinsize
shopt -s histappend
shopt -s cdspell
shopt -s cmdhist
shopt -s extglob
HISTFILESIZE=1000
HISTSIZE=250
HISTCONTROL=ignoreboth:erasedups
export HISTIGNORE="I*:clear:ls*:fg:exit:history*:[ \t]*:&"

# exports
export TERM=xterm-256color
export NCURSES_NO_UTF8_ACS=1
# TODO: add setup functionality to ask if powerline should be on or off
export POWERLINE="ON"
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export PAGER=/usr/bin/less

# clinit
export CLINIT_HOME="${HOME}"/Projects/GitHub/clinit
. "${CLINIT_HOME}"/bash/bsfl
. "${CLINIT_HOME}"/bash/bash_aliases
. "${CLINIT_HOME}"/bash/bash_functions
. "${CLINIT_HOME}"/bash/bash_colors

# prompt
if option_enabled "${POWERLINE}"
then
    # powerline
    powerline-daemon -q
    . /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
elif file_exists "${CLINIT_HOME}"/bash/bash_prompt
then
    # colors prompts
    . "${CLINIT_HOME}"/bash/bash_prompt
fi

